# .circleci/config.yml
version: 2.1
orbs:
  macos: circleci/macos@2
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
#      - macos/switch-ruby
#          version: "2.7.2"
      - run: bundle install
#      - restore_cache
#          key: 1-gems-{{checksum "Gemfile.lock"}}
#      - run: bundle check || bundle install --path vendor/bundle --clean
#      - save_cache:
#          key: 1-gems-{{checksum "Gemfile.lock"}}
#          paths:
#            - vendor/bundle
#      - run: bundle exec pod install
#      - run:
#          name: Fastlane
#          command: bundle exec fastlane $first_lane
#      - store_artifacts:
#          path: output
#      - store_test_results:
#          path: output/scan

workflows:
  build-test-workflows:
    jobs:
      - build-and-test
