# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Description of what the lane does"
  lane :first_lane do
  desc "单元测试"
    scan
  end
  
  lane :second_lane do
  desc "打个包包"
  gym(
       export_method: "development",
       xcode_path: "/Applications/Xcode-14.3.app"
     )
  end
end
